export const strings = {
  play: "Jugar",
  playing: "Ejecutando",
  uninstall: "Desinstalar",
  uninstalling: "Desinstalando...",
  install: "Instalar",
  processing: "Instalando...",
  cancel: "Cancelar",
  cancelling: "Cancelando...",
  advancedOptions: "Opciones avanzadas",
  manualDownload: "Descarga manual",
  selectFile: "Seleccionar archivo",
  changeFile: "Cambiar archivo",
  downloadSpeed: "Velocidad",
  eta: "Tiempo restante",
  downloaded: "Descargado",
  queued: "En cola...",

  preparingMod: "Preparando archivos del mod...",
  extractingBase: "Extrayendo juego base...",
  extractingMod: "Extrayendo mod...",
  mergingBase: "Instalando juego base...",
  mergingMod: "Instalando archivos de traducción...",
  cleaningTemp: "Limpiando archivos temporales...",
  detectingExe: "Detectando ejecutable...",
  installSuccess: "Instalación completada.",
  installFailed: "Instalación fallida.",
  installCancelled: "Instalación cancelada.",

  manualRequired: "Este mod requiere descarga manual. Descarga y selecciona el archivo.",
  localSelected: "Archivo local seleccionado (se instalará sin descargar)",
  autoDownloadInfo: "Este mod se descargará e instalará automáticamente.",
  backgroundInstallStarted: "Instalación iniciada en segundo plano para",
  uninstallCompleted: "Desinstalación completada",
  uninstallRequiredWarn: "No se puede desinstalar el mod mientras se está ejecutando.",
  noScreenshots: "Este mod no tiene capturas de pantalla.",
  screenshots: "Capturas",
  previous: "Anterior",
  next: "Siguiente",
  close: "Cerrar",
  notifications: "Notificaciones",
  showNotifications: "Notificaciones",
  hide: "Ocultar"
};
